[package]
name = "rune-cli"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rune"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
rune-config = { path = "../rune-config" }
rune-out = { path = "../rune-out" }

[dev-dependencies]
regex = { workspace = true }
tempfile = { workspace = true }
unindent = { workspace = true }
