[package]
name = "rune-config"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
oxc = { workspace = true }
oxc_sourcemap = { workspace = true }
rquickjs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
dunce = { workspace = true }
blake3 = { workspace = true }
strsim = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
