import path from 'node:path';
import { defineConfig, type RspressPlugin, type UserConfig } from '@rspress/core';
import { pluginLlms } from '@rspress/plugin-llms';
import { pluginSitemap } from '@rspress/plugin-sitemap';

const SITE_URL = 'https://rune.gio-labs.com';
const AUTHOR_URL = 'https://github.com/giancarlosisasi';
const REPO_URL = 'https://github.com/giancarlosisasi/rune';
const SOCIAL_IMAGE = `${SITE_URL}/og.png`;
const SOCIAL_IMAGE_ALT = 'The runic letter raido above the wordmark rune, on a dark field.';

const structuredData = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'Rune',
  applicationCategory: 'DeveloperApplication',
  operatingSystem: 'Windows, macOS, Linux',
  url: SITE_URL,
  codeRepository: REPO_URL,
  image: SOCIAL_IMAGE,
  description:
    'A script runner for JavaScript and TypeScript monorepos. Commands are defined once in rune.config.ts and referenced by name from every package.',
  author: {
    '@type': 'Person',
    name: 'Giancarlos Isasi',
    url: AUTHOR_URL,
    sameAs: [AUTHOR_URL],
  },
};

/**
 * The one address a page answers on. Rspress gives a section index the route `/cli/`,
 * which `trailingSlash: false` in vercel.json then redirects to `/cli`, so the raw
 * route is never the address to publish.
 */
function canonicalPath(routePath: string): string {
  return routePath.replace(/\.html$/, '').replace(/\/+$/, '') || '/';
}

function canonicalUrl(routePath: string): string {
  return SITE_URL + canonicalPath(routePath);
}

/**
 * The sitemap plugin builds every `loc` from the raw route, so it is fed the same
 * normalized path the canonical link uses. The two cannot drift apart.
 */
function pluginCanonicalSitemap(): RspressPlugin {
  const plugin = pluginSitemap({ siteUrl: SITE_URL });
  return {
    ...plugin,
    extendPageData: (pageData, isProd) =>
      plugin.extendPageData?.({ ...pageData, routePath: canonicalPath(pageData.routePath) }, isProd),
  };
}

const head: UserConfig['head'] = [
  ['meta', { name: 'author', content: 'Giancarlos Isasi' }],
  ['link', { rel: 'author', href: AUTHOR_URL }],

  // Generated by web-assets.json. Regenerate with `pnpm assets` after editing brand/.
  ['link', { rel: 'icon', href: '/favicon.ico', sizes: '48x48' }],
  ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' }],
  ['link', { rel: 'manifest', href: '/site.webmanifest' }],
  ['meta', { name: 'theme-color', content: '#F5F3EF', media: '(prefers-color-scheme: light)' }],
  ['meta', { name: 'theme-color', content: '#0F1215', media: '(prefers-color-scheme: dark)' }],

  ['meta', { property: 'og:site_name', content: 'Rune' }],
  ['meta', { property: 'og:locale', content: 'en_US' }],
  ['meta', { property: 'og:image', content: SOCIAL_IMAGE }],
  ['meta', { property: 'og:image:width', content: '1200' }],
  ['meta', { property: 'og:image:height', content: '630' }],
  ['meta', { property: 'og:image:alt', content: SOCIAL_IMAGE_ALT }],
  ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
  ['meta', { name: 'twitter:image', content: SOCIAL_IMAGE }],
  ['meta', { name: 'twitter:image:alt', content: SOCIAL_IMAGE_ALT }],

  // Rspress writes no canonical of its own, and the function form of `head` is the
  // only hook that sees the route.
  (route) => ['link', { rel: 'canonical', href: canonicalUrl(route.routePath) }],
  (route) => ['meta', { property: 'og:url', content: canonicalUrl(route.routePath) }],
];

const config: UserConfig = {
  root: 'docs',
  base: '/',
  lang: 'en',
  title: 'Rune',
  description:
    'A script runner for JavaScript and TypeScript monorepos. Define a command once, reference it by name from every package.',
  icon: '/favicon.svg',
  logo: { light: '/mark-light.svg', dark: '/mark-dark.svg' },
  logoText: 'rune',
  outDir: 'doc_build',
  siteOrigin: SITE_URL,
  head,
  plugins: [pluginCanonicalSitemap(), pluginLlms()],
  markdown: {
    link: {
      checkDeadLinks: true,
      checkAnchors: true,
    },
    globalComponents: [
      path.resolve(__dirname, 'theme/components/Cards.tsx'),
      path.resolve(__dirname, 'theme/components/Card.tsx'),
      path.resolve(__dirname, 'theme/components/PackageManagerTabs.tsx'),
    ],
  },
  route: {
    cleanUrls: true,
  },
  search: {
    mode: 'local',
  },
  i18nSource: (defaults) => ({
    ...defaults,
    outlineTitle: { ...defaults.outlineTitle, en: 'On this page' },
  }),
  themeConfig: {
    socialLinks: [{ icon: 'github', mode: 'link', content: REPO_URL }],
    enableContentAnimation: false,
    enableAppearanceAnimation: false,
  },
  builderConfig: {
    // `head` entries are tag-plus-attributes only, and JSON-LD needs a body.
    html: {
      tags: [
        {
          tag: 'script',
          attrs: { type: 'application/ld+json' },
          children: JSON.stringify(structuredData),
          head: true,
        },
      ],
    },
  },
};

export default defineConfig(config);
